# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

resources:
  containers:
  - container: battleship
    image: tschissler/battleship-cpp

pool:
  vmImage: 'Ubuntu-latest'

container: battleship

steps:
- script: 'make TestRunner.exe'
  workingDirectory: '$(Build.SourcesDirectory)/MAKE'
  displayName: 'Build testrunner using make'

- script: 'ls'
  workingDirectory: '$(Build.SourcesDirectory)/MAKE'
  displayName: 'ls'
  
- script: './TestRunner.exe XML >> testresults.xml'
  workingDirectory: '$(Build.SourcesDirectory)/MAKE'
  displayName: 'Execute Unit-Tests'

- script: make
  workingDirectory: $(Build.SourcesDirectory)/MAKE
  displayName: 'Build using make'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/testresults.xml'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)/MAKE/*.exe'
    ArtifactName: 'drop'
    publishLocation: 'Container'
